name: BuildAndTest

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: BPCalculatorBOR2021   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'      # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.BPCalculatorBOR2021_7b8c }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: BPCalculator

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # windows-latest
    #environment: production

    steps:
      - uses: actions/checkout@v2
      
      - name: Run unit tests      
        run: dotnet test BPCalculatorTests/BPCalculatorTests.csproj --collect "Code coverage" -l:trx
        # restore not required as it's carried out by the previous job        

      - name: Run Acceptance tests
        run: dotnet test BpAcceptTests/BpAcceptTests.csproj --collect "Code coverage" -l:trx

      #- name: Check env variables values
      #  run: |
      #    echo "GITHUB_ACTION_PATH is $GITHUB_ACTION_PATH"
      #    echo "GITHUB_WORKFLOW is $GITHUB_WORKFLOW"
      #    echo "GITHUB_ACTION is $GITHUB_ACTION"
      #    echo "GITHUB_REPOSITORY is $GITHUB_REPOSITORY"
      #    echo "GITHUB_EVENT_PATH is $GITHUB_EVENT_PATH"
      #    echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"


      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: TestResultsZip
          path: D:\a\bloodPressureCheck\bloodPressureCheck\BpAcceptTests\TestResults\
          # TODO Swap this out for an environment variable

      #- name: Specflow LivngDoc # Not able to point to correct test assembly path
      #  run: |
         #dotnet add package SpecFlow.Plus.LivingDocPlugin
         #dotnet tool install --global SpecFlow.Plus.LivingDoc.cli
         #LivingDoc test-assembly *\BpAcceptTests.dll -t *\TestExecution.json
         

      #- name: Build # Probably safe to delete
      #  run: dotnet build --configuration Release --no-restore 
      # call build with restore to get rid of project.assets.json file missing errors
      

      # CD Section      
      
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'BloodPressureChecker'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7            
          # fail if CVSS score (CVE scoring system) is High >=7
          
      - name: Upload Depcheck Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

      # TODO Deploy to QA
        # Run E2E (Selenium)

      # TODO Deploy to Staging 
        # Run performance tests (k6 cloud)
        # Simple PEN tests (pasive scanning)
        
      # TODO Deploy to prod
        # blue/green, canary
        
      # TODO Telemetry


      - name: Publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 

  # Deploy to Azure Web apps
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
                  
      - name: Publish Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
